global:
  scrape_interval: 15s

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'WIKI01'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.10:9100']

  - job_name: 'WIKI02'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.2.20:9100']

  - job_name: 'SQL'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.3.30:9100']

  - job_name: 'BB_WIKI01'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.10:9155']

  - job_name: 'BB_WIKI02'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.2.20:9155']

  - job_name: 'BB_SQL'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.3.30:9155']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'blackbox_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9115
        labels:
          group: 'production'

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:3000

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
